---
- block:
    - name: Install java
      apt:
        name:
          - openjdk-11-jre
        update_cache: yes
        state: present
      when: ansible_distribution_release == "buster"

    - name: Install java
      apt:
        name:
          - "{{ jreversion }}"
        update_cache: yes
        state: present
      when: ansible_distribution_release == "stretch"

    - name: Jenkins apt-key
      apt_key:
        url: "{{ aptkey }}"
        state: present

    - name: Jenkins repo
      apt_repository:
        repo: "{{ apturl }}"
        state: present

    - name: Install jenkins
      apt:
        name: jenkins
        update_cache: yes
        state: present

    - name: Ensure jenkins is running
      service:
        name: jenkins
        state: started

    - name: Add user to jenkins group
      user:
        name: "{{ user }}"
        groups: jenkins
        append: yes
    
    - name: Install software
      apt:
        name:
          - git
          - maven
        update_cache: yes
        state: present
    
    - name: Pip install ansible
      pip:
        name: ansible
        executable: pip3
      become: true
      become_method: sudo
      become_user: jenkins
  
  tags: rbp
